### ISSUE TITLE
missing remote_address ("client" column in html output)

### ISSUE THREAD

**Issue by gmorten1** [mojolicious/mojo-status#2]
the $tx->remote_address in _tx returns undef, so the IP isn't recorded for the new connection. i can "fix" it by setting remote_address in _request when necessary
    `$_->{workers}{$$}{connections}{$id}{remote_address} ||= $tx->remote_address;
`
but i'm not sure why it was undef or if this indicates a bigger problem

**Comment by kraih** [comment]
Thanks, fixed in the latest release.
